spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/log
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties: {hibernate.temp.use_jdbc_metadata_defaults: false}
  kafka:
    bootstrap-servers: 10.16.90.187:9092
    listener:
      concurrency: 10
      ack-mode: MANUAL_IMMEDIATE
      poll-timeout: 1500
    consumer:
      group-id: logSystem
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties: {session.timeout.ms: 6000, auto.offset.reset: earliest}
logging:
  file: C:/logs/log.log 
  level: 
    com.dt.log: debug 
log: 
  df-kafkaconsumer: 
    topic : dflog
server:
  port: 8083